spring:
  datasource:
    url: jdbc:mysql://localhost:21212/server_monitoring?rewriteBatchedStatements=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tagtag1010

openai:
  api-key: test-key

mcp:
  server-url: http://localhost:8080

forwarder:
  image-url: ghcr.io/takch02/mcp-forwarder:latest
