import http from 'k6/http';
import { check, sleep } from 'k6';
import { randomString } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';

// --- 설정 영역 ---
const BASE_URL = 'http://localhost:8080/api/servers';
const SERVER_NAME = 'target'; // DB에 등록된 서버 이름
const MCP_TOKEN = '1d5e5978-683e-4fdc-9181-27903342c923'; // DB에 저장된 해당 서버의 토큰 (필수!)
const USER_KAKAO_TOKEN = ''; // (선택) 없으면 헤더에서 빼도 됨

// 부하 테스트 시나리오 설정
export const options = {
    scenarios: {
        // 1. 데드락 유발용: 순간적으로 와르르 쏟아붓기 (Spike Test)
        deadlock_spike: {
            executor: 'ramping-vus',
            startVUs: 0,
            stages: [
                { duration: '5s', target: 50 },  // 5초 만에 50명 동시 접속 (급상승)
                { duration: '10s', target: 50 }, // 10초간 유지 (여기서 데드락 터져야 함)
                { duration: '5s', target: 0 },   // 종료
            ],
            gracefulStop: '0s', // 테스트 끝나면 바로 끊기
        },
    },
    // 실패율이 1% 넘으면 테스트 실패로 간주
    thresholds: {
        http_req_failed: ['rate<0.01'],
        http_req_duration: ['p(95)<500'], // 95% 요청이 0.5초 안에 끝나야 함
    },
};

export default function () {
    const url = `${BASE_URL}/${SERVER_NAME}/ingest/logs`;

    const payload = JSON.stringify([
        {
            ts: Date.now(),
            level: 'INFO',
            message: `[K6 Load Test] Log message ${randomString(10)} generated by k6`,
        },
        {
            ts: Date.now(),
            level: 'WARN',
            message: `[K6 Load Test] Warning check ${randomString(8)}`,
        }
    ]);

    const params = {
        headers: {
            'Content-Type': 'application/json',
            'X-MCP-TOKEN': MCP_TOKEN,
            'X-USER-KAKAO-TOKEN': USER_KAKAO_TOKEN,
        },
    };

    // 요청 전송
    const res = http.post(url, payload, params);

    // 결과 검증
    check(res, {
        'status is 200': (r) => r.status === 200,
        'error rate check': (r) => r.status !== 500, // 500 에러(데드락)가 안 나야 함
    });

    // 너무 빠르면 로컬 PC가 못 버틸 수 있으므로 미세한 텀 (0.01초~0.1초)
    sleep(Math.random() * 0.1);
}